### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by faisalahmed95** [sezan92/attention_sezan#1]
how can i install text_preprocess_utils_fh  in my ubuntu environment? Please help me. Thanks in advance

**Comment by sezan92** [comment]
you don't need to. the ```text_preprocess_utils_fh.py``` is given in the repo. by the way,
please remove "/" before the name of folder "data" if you want to run it in your conputer... I.e. "/data/..." → "data/..."

**Comment by faisalahmed95** [comment]
Thanks
