### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by faisalahmed95** [sezan92/attention_sezan#2]
When I give the command python main_bengali_fh.py

> Traceback (most recent call last):
>   File "main_bengali_fh.py", line 14, in <module>
>     import text_preprocess_utils_fh as tpu
> ImportError: No module named text_preprocess_utils_fh

**Comment by sezan92** [comment]
thanks. Please clone type ```git pull origin master ``` in the repo folder .. and please run again

**Comment by faisalahmed95** [comment]
(virtual-py2) faisal@DeepLearning-PC:~/translation$ python main_bengali_fh.py
Using TensorFlow backend.
Reading file.......
Traceback (most recent call last):
  File "main_bengali_fh.py", line 23, in <module>
    tp = tpu.text_prep('data/ben.txt',limit=20000)
  File "/home/faisal/translation/text_preprocess_utils_fh.py", line 22, in __init__
    self.df_test =self.df_actual.sample(500)
  File "/home/faisal/.virtualenvs/virtual-py2/local/lib/python2.7/site-packages/pandas/core/generic.py", line 1978, in __getattr__
    (type(self).__name__, name))
AttributeError: 'DataFrame' object has no attribute 'sample'
Now i face this problem. Please help. Thanks in advance

**Comment by sezan92** [comment]
what's your ```pandas``` version?

**Comment by faisalahmed95** [comment]
pandas 1.11.0

**Comment by sezan92** [comment]
your version seems to be old. Please update pandas , atleast 0.20.0

**Comment by faisalahmed95** [comment]
(virtual-py2) faisal@DeepLearning-PC:~/translation$ python attention_test_fh.py
/home/faisal/.virtualenvs/virtual-py2/local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "attention_test_fh.py", line 12, in <module>
    import text_preprocess_utils as tpu
ImportError: No module named text_preprocess_utils
Please help.

**Comment by faisalahmed95** [comment]
Thank you so much.
